### ISSUE TITLE
Check unsaved files

### ISSUE THREAD

**Issue by jacksonrayhamilton** [lbolla/emacs-flycheck-elixir#4]
Currently this checker only reports errors when the file is saved, which can be pretty confusing if you aren't used to that (most Flycheck checkers I've used work on unsaved files).

I've heard that `elixirc` doesn't support compiling from stdin. However, is it possible to check files using Flycheck's temporary files (e.g. [`source` or `source-inplace`](https://github.com/flycheck/flycheck/blob/0046f0ee7aed376c9a328db0ae9f7803c6cc5f46/flycheck.el#L4449))? I tried changing this package's `:command` to `(... source-inplace)` and it seemed to work on a single file.

**Comment by lbolla** [comment]
Thanks!
