### ISSUE TITLE
Dependencies are not found for umbrella applications

### ISSUE THREAD

**Issue by christopher-dG** [lbolla/emacs-flycheck-elixir#7]
Umbrella applications by default store their built dependencies at the umbrella root rather than per-project, which is making Flycheck emit "module X is not loaded and could not be found" for any external dependencies.
I'm not sure if it's feasible to read `mix.exs` inside `elixirc-params` but there's a `build_path` in there which would help.

Here's an umbrella app to illustrate:

```
.
├── apps
│   └── bar  # There's no _build in here.
│       ├── config
│       │   └── config.exs
│       ├── lib
│       │   └── bar.ex
│       ├── mix.exs
│       ├── README.md
│       └── test
│           ├── bar_test.exs
│           └── test_helper.exs
├── _build  # Here it is!
│   └── dev
│       ├── consolidated
│       │   ├── Elixir.Collectable.beam
│       │   ├── Elixir.Enumerable.beam
│       │   ├── Elixir.IEx.Info.beam
│       │   ├── Elixir.Inspect.beam
│       │   ├── Elixir.List.Chars.beam
│       │   └── Elixir.String.Chars.beam
│       └── lib
│           └── bar
│               └── ebin
│                   ├── bar.app
│                   └── Elixir.Bar.beam
├── config
│   └── config.exs
├── mix.exs
└── README.md
```

**Comment by lbolla** [comment]
I don't use Elixir anymore, but I am happy to accept PRs!

**Comment by Coffei** [comment]
Must get my eyes checked, since I just opened a new issue regarding the same.
I have a fix so I'll submit a PR soon.
